/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  dev.sefiraat.netheopoiesis.api.items.HarvestableSeed
 *  dev.sefiraat.netheopoiesis.api.plant.Growth
 *  dev.sefiraat.netheopoiesis.api.plant.GrowthStages
 *  dev.sefiraat.netheopoiesis.api.plant.Placements
 *  dev.sefiraat.netheopoiesis.implementation.Stacks
 *  dev.sefiraat.netheopoiesis.utils.Skulls
 *  dev.sefiraat.netheopoiesis.utils.Theme
 *  io.github.thebusybiscuit.slimefun4.api.SlimefunAddon
 *  io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack
 *  lombok.Generated
 *  org.bukkit.inventory.ItemStack
 */
package io.github.sefiraat.crystamaehistoria.slimefun;

import dev.sefiraat.netheopoiesis.api.items.HarvestableSeed;
import dev.sefiraat.netheopoiesis.api.plant.Growth;
import dev.sefiraat.netheopoiesis.api.plant.GrowthStages;
import dev.sefiraat.netheopoiesis.api.plant.Placements;
import dev.sefiraat.netheopoiesis.implementation.Stacks;
import dev.sefiraat.netheopoiesis.utils.Skulls;
import dev.sefiraat.netheopoiesis.utils.Theme;
import io.github.sefiraat.crystamaehistoria.CrystamaeHistoria;
import io.github.sefiraat.crystamaehistoria.slimefun.Materials;
import io.github.sefiraat.crystamaehistoria.stories.definition.StoryRarity;
import io.github.sefiraat.crystamaehistoria.stories.definition.StoryType;
import io.github.thebusybiscuit.slimefun4.api.SlimefunAddon;
import io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack;
import lombok.Generated;
import org.bukkit.inventory.ItemStack;

public final class NetheoPlants {
    public static final SlimefunItemStack ELEMENTAL_COMMON_SEED = Theme.themedSeed((String)"CRY_ELEMENTAL_COMMON_SEED", (ItemStack)Skulls.SEED_RED.getPlayerHead(), (Theme)Theme.SEED, (String)"Common Elemental Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Elemental Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack MECHANICAL_COMMON_SEED = Theme.themedSeed((String)"CRY_MECHANICAL_COMMON_SEED", (ItemStack)Skulls.SEED_ORANGE.getPlayerHead(), (Theme)Theme.SEED, (String)"Common Mechanical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Mechanical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ALCHEMICAL_COMMON_SEED = Theme.themedSeed((String)"CRY_ALCHEMICAL_COMMON_SEED", (ItemStack)Skulls.SEED_YELLOW.getPlayerHead(), (Theme)Theme.SEED, (String)"Common Alchemical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Alchemical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack HISTORICAL_COMMON_SEED = Theme.themedSeed((String)"CRY_HISTORICAL_COMMON_SEED", (ItemStack)Skulls.SEED_GREEN.getPlayerHead(), (Theme)Theme.SEED, (String)"Common Historical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Historical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack HUMAN_COMMON_SEED = Theme.themedSeed((String)"CRY_HUMAN_COMMON_SEED", (ItemStack)Skulls.SEED_BLUE.getPlayerHead(), (Theme)Theme.SEED, (String)"Common Human Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Human Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ANIMAL_COMMON_SEED = Theme.themedSeed((String)"CRY_ANIMAL_COMMON_SEED", (ItemStack)Skulls.SEED_CYAN.getPlayerHead(), (Theme)Theme.SEED, (String)"Common Animal Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Animal Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack CELESTIAL_COMMON_SEED = Theme.themedSeed((String)"CRY_CELESTIAL_COMMON_SEED", (ItemStack)Skulls.SEED_YELLOW.getPlayerHead(), (Theme)Theme.SEED, (String)"Common Celestial Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Celestial Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack VOID_COMMON_SEED = Theme.themedSeed((String)"CRY_VOID_COMMON_SEED", (ItemStack)Skulls.SEED_PURPLE.getPlayerHead(), (Theme)Theme.SEED, (String)"Common Void Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Void Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack PHILOSOPHICAL_COMMON_SEED = Theme.themedSeed((String)"CRY_PHILOSOPHICAL_COMMON_SEED", (ItemStack)Skulls.SEED_PURPLE.getPlayerHead(), (Theme)Theme.SEED, (String)"Common Philosophical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Philosophical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ELEMENTAL_UNCOMMON_SEED = Theme.themedSeed((String)"CRY_ELEMENTAL_UNCOMMON_SEED", (ItemStack)Skulls.SEED_RED.getPlayerHead(), (Theme)Theme.SEED, (String)"Uncommon Elemental Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Elemental Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack MECHANICAL_UNCOMMON_SEED = Theme.themedSeed((String)"CRY_MECHANICAL_UNCOMMON_SEED", (ItemStack)Skulls.SEED_ORANGE.getPlayerHead(), (Theme)Theme.SEED, (String)"Uncommon Mechanical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Mechanical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ALCHEMICAL_UNCOMMON_SEED = Theme.themedSeed((String)"CRY_ALCHEMICAL_UNCOMMON_SEED", (ItemStack)Skulls.SEED_YELLOW.getPlayerHead(), (Theme)Theme.SEED, (String)"Uncommon Alchemical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Alchemical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack HISTORICAL_UNCOMMON_SEED = Theme.themedSeed((String)"CRY_HISTORICAL_UNCOMMON_SEED", (ItemStack)Skulls.SEED_GREEN.getPlayerHead(), (Theme)Theme.SEED, (String)"Uncommon Historical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Historical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack HUMAN_UNCOMMON_SEED = Theme.themedSeed((String)"CRY_HUMAN_UNCOMMON_SEED", (ItemStack)Skulls.SEED_BLUE.getPlayerHead(), (Theme)Theme.SEED, (String)"Uncommon Human Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Human Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ANIMAL_UNCOMMON_SEED = Theme.themedSeed((String)"CRY_ANIMAL_UNCOMMON_SEED", (ItemStack)Skulls.SEED_CYAN.getPlayerHead(), (Theme)Theme.SEED, (String)"Uncommon Animal Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Animal Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack CELESTIAL_UNCOMMON_SEED = Theme.themedSeed((String)"CRY_CELESTIAL_UNCOMMON_SEED", (ItemStack)Skulls.SEED_YELLOW.getPlayerHead(), (Theme)Theme.SEED, (String)"Uncommon Celestial Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Celestial Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack VOID_UNCOMMON_SEED = Theme.themedSeed((String)"CRY_VOID_UNCOMMON_SEED", (ItemStack)Skulls.SEED_PURPLE.getPlayerHead(), (Theme)Theme.SEED, (String)"Uncommon Void Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Void Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack PHILOSOPHICAL_UNCOMMON_SEED = Theme.themedSeed((String)"CRY_PHILOSOPHICAL_UNCOMMON_SEED", (ItemStack)Skulls.SEED_PURPLE.getPlayerHead(), (Theme)Theme.SEED, (String)"Uncommon Philosophical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Philosophical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ELEMENTAL_RARE_SEED = Theme.themedSeed((String)"CRY_ELEMENTAL_RARE_SEED", (ItemStack)Skulls.SEED_RED.getPlayerHead(), (Theme)Theme.SEED, (String)"Rare Elemental Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Elemental Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack MECHANICAL_RARE_SEED = Theme.themedSeed((String)"CRY_MECHANICAL_RARE_SEED", (ItemStack)Skulls.SEED_ORANGE.getPlayerHead(), (Theme)Theme.SEED, (String)"Rare Mechanical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Mechanical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ALCHEMICAL_RARE_SEED = Theme.themedSeed((String)"CRY_ALCHEMICAL_RARE_SEED", (ItemStack)Skulls.SEED_YELLOW.getPlayerHead(), (Theme)Theme.SEED, (String)"Rare Alchemical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Alchemical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack HISTORICAL_RARE_SEED = Theme.themedSeed((String)"CRY_HISTORICAL_RARE_SEED", (ItemStack)Skulls.SEED_GREEN.getPlayerHead(), (Theme)Theme.SEED, (String)"Rare Historical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Historical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack HUMAN_RARE_SEED = Theme.themedSeed((String)"CRY_HUMAN_RARE_SEED", (ItemStack)Skulls.SEED_BLUE.getPlayerHead(), (Theme)Theme.SEED, (String)"Rare Human Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Human Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ANIMAL_RARE_SEED = Theme.themedSeed((String)"CRY_ANIMAL_RARE_SEED", (ItemStack)Skulls.SEED_CYAN.getPlayerHead(), (Theme)Theme.SEED, (String)"Rare Animal Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Animal Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack CELESTIAL_RARE_SEED = Theme.themedSeed((String)"CRY_CELESTIAL_RARE_SEED", (ItemStack)Skulls.SEED_YELLOW.getPlayerHead(), (Theme)Theme.SEED, (String)"Rare Celestial Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Celestial Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack VOID_RARE_SEED = Theme.themedSeed((String)"CRY_VOID_RARE_SEED", (ItemStack)Skulls.SEED_PURPLE.getPlayerHead(), (Theme)Theme.SEED, (String)"Rare Void Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Void Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack PHILOSOPHICAL_RARE_SEED = Theme.themedSeed((String)"CRY_PHILOSOPHICAL_RARE_SEED", (ItemStack)Skulls.SEED_PURPLE.getPlayerHead(), (Theme)Theme.SEED, (String)"Rare Philosophical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Philosophical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ELEMENTAL_EPIC_SEED = Theme.themedSeed((String)"CRY_ELEMENTAL_EPIC_SEED", (ItemStack)Skulls.SEED_RED.getPlayerHead(), (Theme)Theme.SEED, (String)"Epic Elemental Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Elemental Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack MECHANICAL_EPIC_SEED = Theme.themedSeed((String)"CRY_MECHANICAL_EPIC_SEED", (ItemStack)Skulls.SEED_ORANGE.getPlayerHead(), (Theme)Theme.SEED, (String)"Epic Mechanical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Mechanical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ALCHEMICAL_EPIC_SEED = Theme.themedSeed((String)"CRY_ALCHEMICAL_EPIC_SEED", (ItemStack)Skulls.SEED_YELLOW.getPlayerHead(), (Theme)Theme.SEED, (String)"Epic Alchemical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Alchemical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack HISTORICAL_EPIC_SEED = Theme.themedSeed((String)"CRY_HISTORICAL_EPIC_SEED", (ItemStack)Skulls.SEED_GREEN.getPlayerHead(), (Theme)Theme.SEED, (String)"Epic Historical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Historical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack HUMAN_EPIC_SEED = Theme.themedSeed((String)"CRY_HUMAN_EPIC_SEED", (ItemStack)Skulls.SEED_BLUE.getPlayerHead(), (Theme)Theme.SEED, (String)"Epic Human Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Human Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ANIMAL_EPIC_SEED = Theme.themedSeed((String)"CRY_ANIMAL_EPIC_SEED", (ItemStack)Skulls.SEED_CYAN.getPlayerHead(), (Theme)Theme.SEED, (String)"Epic Animal Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Animal Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack CELESTIAL_EPIC_SEED = Theme.themedSeed((String)"CRY_CELESTIAL_EPIC_SEED", (ItemStack)Skulls.SEED_YELLOW.getPlayerHead(), (Theme)Theme.SEED, (String)"Epic Celestial Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Celestial Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack VOID_EPIC_SEED = Theme.themedSeed((String)"CRY_VOID_EPIC_SEED", (ItemStack)Skulls.SEED_PURPLE.getPlayerHead(), (Theme)Theme.SEED, (String)"Epic Void Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Void Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack PHILOSOPHICAL_EPIC_SEED = Theme.themedSeed((String)"CRY_PHILOSOPHICAL_EPIC_SEED", (ItemStack)Skulls.SEED_PURPLE.getPlayerHead(), (Theme)Theme.SEED, (String)"Epic Philosophical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Philosophical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ELEMENTAL_MYTHICAL_SEED = Theme.themedSeed((String)"CRY_ELEMENTAL_MYTHICAL_SEED", (ItemStack)Skulls.SEED_RED.getPlayerHead(), (Theme)Theme.SEED, (String)"Mythical Elemental Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Elemental Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack MECHANICAL_MYTHICAL_SEED = Theme.themedSeed((String)"CRY_MECHANICAL_MYTHICAL_SEED", (ItemStack)Skulls.SEED_ORANGE.getPlayerHead(), (Theme)Theme.SEED, (String)"Mythical Mechanical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Mechanical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ALCHEMICAL_MYTHICAL_SEED = Theme.themedSeed((String)"CRY_ALCHEMICAL_MYTHICAL_SEED", (ItemStack)Skulls.SEED_YELLOW.getPlayerHead(), (Theme)Theme.SEED, (String)"Mythical Alchemical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Alchemical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack HISTORICAL_MYTHICAL_SEED = Theme.themedSeed((String)"CRY_HISTORICAL_MYTHICAL_SEED", (ItemStack)Skulls.SEED_GREEN.getPlayerHead(), (Theme)Theme.SEED, (String)"Mythical Historical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Historical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack HUMAN_MYTHICAL_SEED = Theme.themedSeed((String)"CRY_HUMAN_MYTHICAL_SEED", (ItemStack)Skulls.SEED_BLUE.getPlayerHead(), (Theme)Theme.SEED, (String)"Mythical Human Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Human Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack ANIMAL_MYTHICAL_SEED = Theme.themedSeed((String)"CRY_ANIMAL_MYTHICAL_SEED", (ItemStack)Skulls.SEED_CYAN.getPlayerHead(), (Theme)Theme.SEED, (String)"Mythical Animal Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Animal Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack CELESTIAL_MYTHICAL_SEED = Theme.themedSeed((String)"CRY_CELESTIAL_MYTHICAL_SEED", (ItemStack)Skulls.SEED_YELLOW.getPlayerHead(), (Theme)Theme.SEED, (String)"Mythical Celestial Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Celestial Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack VOID_MYTHICAL_SEED = Theme.themedSeed((String)"CRY_VOID_MYTHICAL_SEED", (ItemStack)Skulls.SEED_PURPLE.getPlayerHead(), (Theme)Theme.SEED, (String)"Mythical Void Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Void Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));
    public static final SlimefunItemStack PHILOSOPHICAL_MYTHICAL_SEED = Theme.themedSeed((String)"CRY_PHILOSOPHICAL_MYTHICAL_SEED", (ItemStack)Skulls.SEED_PURPLE.getPlayerHead(), (Theme)Theme.SEED, (String)"Mythical Philosophical Crysta Seed", (String[])new String[]{"This seed, when fully grown, will", "provide Philosophical Crysta when", "harvested."}, (String[])Stacks.getCanBePlacedOnLore((String[])new String[]{"Nether Grass (or better)"}));

    public static void setup() {
        CrystamaeHistoria plugin = CrystamaeHistoria.getInstance();
        new HarvestableSeed(ELEMENTAL_COMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.COMMON).get((Object)StoryType.ELEMENTAL).getItem()).setGrowth(new Growth(GrowthStages.VINEY_RED, Placements.NETHER_GRASS_AND_UP, 5, 0.05)).addBreedingPair(Stacks.CRYSTALLINE_SEED.getItemId(), Stacks.CRYSTALLINE_SEED.getItemId(), 0.1, 0.0).addFlavourProfile(5, 2, 2, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(MECHANICAL_COMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.COMMON).get((Object)StoryType.MECHANICAL).getItem()).setGrowth(new Growth(GrowthStages.VINEY_ORANGE, Placements.NETHER_GRASS_AND_UP, 5, 0.05)).addBreedingPair(Stacks.CRYSTALLINE_SEED.getItemId(), Stacks.CRYSTALLINE_SEED.getItemId(), 0.1, 0.0).addFlavourProfile(2, 5, 2, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ALCHEMICAL_COMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.COMMON).get((Object)StoryType.ALCHEMICAL).getItem()).setGrowth(new Growth(GrowthStages.VINEY_YELLOW, Placements.NETHER_GRASS_AND_UP, 5, 0.05)).addBreedingPair(Stacks.CRYSTALLINE_SEED.getItemId(), Stacks.CRYSTALLINE_SEED.getItemId(), 0.1, 0.0).addFlavourProfile(2, 2, 5, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(HISTORICAL_COMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.COMMON).get((Object)StoryType.HISTORICAL).getItem()).setGrowth(new Growth(GrowthStages.VINEY_GREEN, Placements.NETHER_GRASS_AND_UP, 5, 0.05)).addBreedingPair(Stacks.CRYSTALLINE_SEED.getItemId(), Stacks.CRYSTALLINE_SEED.getItemId(), 0.1, 0.0).addFlavourProfile(2, 2, 2, 5, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(HUMAN_COMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.COMMON).get((Object)StoryType.HUMAN).getItem()).setGrowth(new Growth(GrowthStages.VINEY_BLUE, Placements.NETHER_GRASS_AND_UP, 5, 0.05)).addBreedingPair(Stacks.CRYSTALLINE_SEED.getItemId(), Stacks.CRYSTALLINE_SEED.getItemId(), 0.1, 0.0).addFlavourProfile(2, 2, 2, 2, 5).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ANIMAL_COMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.COMMON).get((Object)StoryType.ANIMAL).getItem()).setGrowth(new Growth(GrowthStages.VINEY_CYAN, Placements.NETHER_GRASS_AND_UP, 5, 0.05)).addBreedingPair(Stacks.CRYSTALLINE_SEED.getItemId(), Stacks.CRYSTALLINE_SEED.getItemId(), 0.1, 0.0).addFlavourProfile(4, 4, 3, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(CELESTIAL_COMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.COMMON).get((Object)StoryType.CELESTIAL).getItem()).setGrowth(new Growth(GrowthStages.VINEY_YELLOW, Placements.NETHER_GRASS_AND_UP, 5, 0.05)).addBreedingPair(Stacks.CRYSTALLINE_SEED.getItemId(), Stacks.CRYSTALLINE_SEED.getItemId(), 0.1, 0.0).addFlavourProfile(2, 4, 4, 3, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(VOID_COMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.COMMON).get((Object)StoryType.VOID).getItem()).setGrowth(new Growth(GrowthStages.VINEY_PURPLE, Placements.NETHER_GRASS_AND_UP, 5, 0.05)).addBreedingPair(Stacks.CRYSTALLINE_SEED.getItemId(), Stacks.CRYSTALLINE_SEED.getItemId(), 0.1, 0.0).addFlavourProfile(2, 2, 4, 4, 3).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(PHILOSOPHICAL_COMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.COMMON).get((Object)StoryType.PHILOSOPHICAL).getItem()).setGrowth(new Growth(GrowthStages.VINEY_PURPLE, Placements.NETHER_GRASS_AND_UP, 5, 0.05)).addBreedingPair(Stacks.CRYSTALLINE_SEED.getItemId(), Stacks.CRYSTALLINE_SEED.getItemId(), 0.1, 0.0).addFlavourProfile(3, 2, 2, 4, 4).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ELEMENTAL_UNCOMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.UNCOMMON).get((Object)StoryType.ELEMENTAL).getItem()).setGrowth(new Growth(GrowthStages.FUNGAL_RED, Placements.NETHER_GRASS_AND_UP, 10, 0.01)).addBreedingPair(ELEMENTAL_COMMON_SEED.getItemId(), ELEMENTAL_COMMON_SEED.getItemId(), 0.05, 0.01).addFlavourProfile(10, 2, 2, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(MECHANICAL_UNCOMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.UNCOMMON).get((Object)StoryType.MECHANICAL).getItem()).setGrowth(new Growth(GrowthStages.FUNGAL_ORANGE, Placements.NETHER_GRASS_AND_UP, 10, 0.01)).addBreedingPair(MECHANICAL_COMMON_SEED.getItemId(), MECHANICAL_COMMON_SEED.getItemId(), 0.05, 0.01).addFlavourProfile(2, 10, 2, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ALCHEMICAL_UNCOMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.UNCOMMON).get((Object)StoryType.ALCHEMICAL).getItem()).setGrowth(new Growth(GrowthStages.FUNGAL_YELLOW, Placements.NETHER_GRASS_AND_UP, 10, 0.01)).addBreedingPair(ALCHEMICAL_COMMON_SEED.getItemId(), ALCHEMICAL_COMMON_SEED.getItemId(), 0.05, 0.01).addFlavourProfile(2, 2, 10, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(HISTORICAL_UNCOMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.UNCOMMON).get((Object)StoryType.HISTORICAL).getItem()).setGrowth(new Growth(GrowthStages.FUNGAL_GREEN, Placements.NETHER_GRASS_AND_UP, 10, 0.01)).addBreedingPair(HISTORICAL_COMMON_SEED.getItemId(), HISTORICAL_COMMON_SEED.getItemId(), 0.05, 0.01).addFlavourProfile(2, 2, 2, 10, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(HUMAN_UNCOMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.UNCOMMON).get((Object)StoryType.HUMAN).getItem()).setGrowth(new Growth(GrowthStages.FUNGAL_BLUE, Placements.NETHER_GRASS_AND_UP, 10, 0.01)).addBreedingPair(HUMAN_COMMON_SEED.getItemId(), HUMAN_COMMON_SEED.getItemId(), 0.05, 0.01).addFlavourProfile(2, 2, 2, 2, 10).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ANIMAL_UNCOMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.UNCOMMON).get((Object)StoryType.ANIMAL).getItem()).setGrowth(new Growth(GrowthStages.FUNGAL_CYAN, Placements.NETHER_GRASS_AND_UP, 10, 0.01)).addBreedingPair(ANIMAL_COMMON_SEED.getItemId(), ANIMAL_COMMON_SEED.getItemId(), 0.05, 0.01).addFlavourProfile(6, 6, 4, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(CELESTIAL_UNCOMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.UNCOMMON).get((Object)StoryType.CELESTIAL).getItem()).setGrowth(new Growth(GrowthStages.FUNGAL_YELLOW, Placements.NETHER_GRASS_AND_UP, 10, 0.01)).addBreedingPair(CELESTIAL_COMMON_SEED.getItemId(), CELESTIAL_COMMON_SEED.getItemId(), 0.05, 0.01).addFlavourProfile(2, 6, 6, 4, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(VOID_UNCOMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.UNCOMMON).get((Object)StoryType.VOID).getItem()).setGrowth(new Growth(GrowthStages.FUNGAL_PURPLE, Placements.NETHER_GRASS_AND_UP, 10, 0.01)).addBreedingPair(VOID_COMMON_SEED.getItemId(), VOID_COMMON_SEED.getItemId(), 0.05, 0.01).addFlavourProfile(2, 2, 6, 6, 4).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(PHILOSOPHICAL_UNCOMMON_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.UNCOMMON).get((Object)StoryType.PHILOSOPHICAL).getItem()).setGrowth(new Growth(GrowthStages.FUNGAL_PURPLE, Placements.NETHER_GRASS_AND_UP, 10, 0.01)).addBreedingPair(PHILOSOPHICAL_COMMON_SEED.getItemId(), PHILOSOPHICAL_COMMON_SEED.getItemId(), 0.05, 0.01).addFlavourProfile(4, 2, 2, 6, 6).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ELEMENTAL_RARE_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.RARE).get((Object)StoryType.ELEMENTAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_RED, Placements.NETHER_GRASS_AND_UP, 10, 0.005)).addBreedingPair(ELEMENTAL_UNCOMMON_SEED.getItemId(), ELEMENTAL_UNCOMMON_SEED.getItemId(), 0.025, 0.005).addFlavourProfile(20, 2, 2, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(MECHANICAL_RARE_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.RARE).get((Object)StoryType.MECHANICAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_ORANGE, Placements.NETHER_GRASS_AND_UP, 10, 0.005)).addBreedingPair(MECHANICAL_UNCOMMON_SEED.getItemId(), MECHANICAL_UNCOMMON_SEED.getItemId(), 0.025, 0.005).addFlavourProfile(2, 20, 2, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ALCHEMICAL_RARE_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.RARE).get((Object)StoryType.ALCHEMICAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_YELLOW, Placements.NETHER_GRASS_AND_UP, 10, 0.005)).addBreedingPair(ALCHEMICAL_UNCOMMON_SEED.getItemId(), ALCHEMICAL_UNCOMMON_SEED.getItemId(), 0.025, 0.005).addFlavourProfile(2, 2, 20, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(HISTORICAL_RARE_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.RARE).get((Object)StoryType.HISTORICAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_GREEN, Placements.NETHER_GRASS_AND_UP, 10, 0.005)).addBreedingPair(HISTORICAL_UNCOMMON_SEED.getItemId(), HISTORICAL_UNCOMMON_SEED.getItemId(), 0.025, 0.005).addFlavourProfile(2, 2, 2, 20, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(HUMAN_RARE_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.RARE).get((Object)StoryType.HUMAN).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_BLUE, Placements.NETHER_GRASS_AND_UP, 10, 0.005)).addBreedingPair(HUMAN_UNCOMMON_SEED.getItemId(), HUMAN_UNCOMMON_SEED.getItemId(), 0.025, 0.005).addFlavourProfile(2, 2, 2, 2, 20).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ANIMAL_RARE_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.RARE).get((Object)StoryType.ANIMAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_CYAN, Placements.NETHER_GRASS_AND_UP, 10, 0.005)).addBreedingPair(ANIMAL_UNCOMMON_SEED.getItemId(), ANIMAL_UNCOMMON_SEED.getItemId(), 0.025, 0.005).addFlavourProfile(10, 10, 6, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(CELESTIAL_RARE_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.RARE).get((Object)StoryType.CELESTIAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_YELLOW, Placements.NETHER_GRASS_AND_UP, 10, 0.005)).addBreedingPair(CELESTIAL_UNCOMMON_SEED.getItemId(), CELESTIAL_UNCOMMON_SEED.getItemId(), 0.025, 0.005).addFlavourProfile(2, 10, 10, 6, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(VOID_RARE_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.RARE).get((Object)StoryType.VOID).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_PURPLE, Placements.NETHER_GRASS_AND_UP, 10, 0.005)).addBreedingPair(VOID_UNCOMMON_SEED.getItemId(), VOID_UNCOMMON_SEED.getItemId(), 0.025, 0.005).addFlavourProfile(2, 2, 10, 10, 6).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(PHILOSOPHICAL_RARE_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.RARE).get((Object)StoryType.PHILOSOPHICAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_PURPLE, Placements.NETHER_GRASS_AND_UP, 10, 0.005)).addBreedingPair(PHILOSOPHICAL_UNCOMMON_SEED.getItemId(), PHILOSOPHICAL_UNCOMMON_SEED.getItemId(), 0.025, 0.005).addFlavourProfile(6, 2, 2, 10, 10).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ELEMENTAL_EPIC_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.EPIC).get((Object)StoryType.ELEMENTAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_RED, Placements.NETHER_GRASS_AND_UP, 20, 0.0025)).addBreedingPair(ELEMENTAL_RARE_SEED.getItemId(), ELEMENTAL_RARE_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(20, 2, 2, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(MECHANICAL_EPIC_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.EPIC).get((Object)StoryType.MECHANICAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_ORANGE, Placements.NETHER_GRASS_AND_UP, 20, 0.0025)).addBreedingPair(MECHANICAL_RARE_SEED.getItemId(), MECHANICAL_RARE_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 20, 2, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ALCHEMICAL_EPIC_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.EPIC).get((Object)StoryType.ALCHEMICAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_YELLOW, Placements.NETHER_GRASS_AND_UP, 20, 0.0025)).addBreedingPair(ALCHEMICAL_RARE_SEED.getItemId(), ALCHEMICAL_RARE_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 2, 20, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(HISTORICAL_EPIC_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.EPIC).get((Object)StoryType.HISTORICAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_GREEN, Placements.NETHER_GRASS_AND_UP, 20, 0.0025)).addBreedingPair(HISTORICAL_RARE_SEED.getItemId(), HISTORICAL_RARE_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 2, 2, 20, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(HUMAN_EPIC_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.EPIC).get((Object)StoryType.HUMAN).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_BLUE, Placements.NETHER_GRASS_AND_UP, 20, 0.0025)).addBreedingPair(HUMAN_RARE_SEED.getItemId(), HUMAN_RARE_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 2, 2, 2, 20).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ANIMAL_EPIC_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.EPIC).get((Object)StoryType.ANIMAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_CYAN, Placements.NETHER_GRASS_AND_UP, 20, 0.0025)).addBreedingPair(ANIMAL_RARE_SEED.getItemId(), ANIMAL_RARE_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(20, 20, 6, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(CELESTIAL_EPIC_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.EPIC).get((Object)StoryType.CELESTIAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_YELLOW, Placements.NETHER_GRASS_AND_UP, 20, 0.0025)).addBreedingPair(CELESTIAL_RARE_SEED.getItemId(), CELESTIAL_RARE_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 20, 20, 6, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(VOID_EPIC_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.EPIC).get((Object)StoryType.VOID).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_PURPLE, Placements.NETHER_GRASS_AND_UP, 20, 0.0025)).addBreedingPair(VOID_RARE_SEED.getItemId(), VOID_RARE_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 2, 20, 20, 6).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(PHILOSOPHICAL_EPIC_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.EPIC).get((Object)StoryType.PHILOSOPHICAL).getItem()).setGrowth(new Growth(GrowthStages.SPIKEY_PURPLE, Placements.NETHER_GRASS_AND_UP, 20, 0.0025)).addBreedingPair(PHILOSOPHICAL_RARE_SEED.getItemId(), PHILOSOPHICAL_RARE_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(6, 2, 2, 20, 20).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ELEMENTAL_MYTHICAL_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.MYTHICAL).get((Object)StoryType.ELEMENTAL).getItem()).setGrowth(new Growth(GrowthStages.SPAWNING_RED, Placements.NETHER_GRASS_AND_UP, 30, 0.0025)).addBreedingPair(ELEMENTAL_EPIC_SEED.getItemId(), ELEMENTAL_EPIC_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(30, 2, 2, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(MECHANICAL_MYTHICAL_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.MYTHICAL).get((Object)StoryType.MECHANICAL).getItem()).setGrowth(new Growth(GrowthStages.SPAWNING_ORANGE, Placements.NETHER_GRASS_AND_UP, 30, 0.0025)).addBreedingPair(MECHANICAL_EPIC_SEED.getItemId(), MECHANICAL_EPIC_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 30, 2, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ALCHEMICAL_MYTHICAL_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.MYTHICAL).get((Object)StoryType.ALCHEMICAL).getItem()).setGrowth(new Growth(GrowthStages.SPAWNING_YELLOW, Placements.NETHER_GRASS_AND_UP, 30, 0.0025)).addBreedingPair(ALCHEMICAL_EPIC_SEED.getItemId(), ALCHEMICAL_EPIC_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 2, 30, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(HISTORICAL_MYTHICAL_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.MYTHICAL).get((Object)StoryType.HISTORICAL).getItem()).setGrowth(new Growth(GrowthStages.SPAWNING_GREEN, Placements.NETHER_GRASS_AND_UP, 30, 0.0025)).addBreedingPair(HISTORICAL_EPIC_SEED.getItemId(), HISTORICAL_EPIC_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 2, 2, 30, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(HUMAN_MYTHICAL_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.MYTHICAL).get((Object)StoryType.HUMAN).getItem()).setGrowth(new Growth(GrowthStages.SPAWNING_BLUE, Placements.NETHER_GRASS_AND_UP, 30, 0.0025)).addBreedingPair(HUMAN_EPIC_SEED.getItemId(), HUMAN_EPIC_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 2, 2, 2, 30).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(ANIMAL_MYTHICAL_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.MYTHICAL).get((Object)StoryType.ANIMAL).getItem()).setGrowth(new Growth(GrowthStages.SPAWNING_CYAN, Placements.NETHER_GRASS_AND_UP, 30, 0.0025)).addBreedingPair(ANIMAL_EPIC_SEED.getItemId(), ANIMAL_EPIC_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(30, 30, 6, 2, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(CELESTIAL_MYTHICAL_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.MYTHICAL).get((Object)StoryType.CELESTIAL).getItem()).setGrowth(new Growth(GrowthStages.SPAWNING_YELLOW, Placements.NETHER_GRASS_AND_UP, 30, 0.0025)).addBreedingPair(CELESTIAL_EPIC_SEED.getItemId(), CELESTIAL_EPIC_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 30, 30, 6, 2).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(VOID_MYTHICAL_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.MYTHICAL).get((Object)StoryType.VOID).getItem()).setGrowth(new Growth(GrowthStages.SPAWNING_PURPLE, Placements.NETHER_GRASS_AND_UP, 30, 0.0025)).addBreedingPair(VOID_EPIC_SEED.getItemId(), VOID_EPIC_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(2, 2, 30, 30, 6).tryRegister((SlimefunAddon)plugin);
        new HarvestableSeed(PHILOSOPHICAL_MYTHICAL_SEED).setHarvestingResult(Materials.CRYSTAL_MAP.get((Object)StoryRarity.MYTHICAL).get((Object)StoryType.PHILOSOPHICAL).getItem()).setGrowth(new Growth(GrowthStages.SPAWNING_PURPLE, Placements.NETHER_GRASS_AND_UP, 30, 0.0025)).addBreedingPair(PHILOSOPHICAL_EPIC_SEED.getItemId(), PHILOSOPHICAL_EPIC_SEED.getItemId(), 0.001, 0.0025).addFlavourProfile(6, 2, 2, 30, 30).tryRegister((SlimefunAddon)plugin);
    }

    @Generated
    private NetheoPlants() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }
}

